[2020-11-28 19:25:58,571] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Write_data_to_postgres_then_to_elasticsearch.Write_csv_data_to_db 2020-11-28T13:55:46.743057+00:00 [queued]>
[2020-11-28 19:25:58,592] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Write_data_to_postgres_then_to_elasticsearch.Write_csv_data_to_db 2020-11-28T13:55:46.743057+00:00 [queued]>
[2020-11-28 19:25:58,592] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-11-28 19:25:58,592] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-11-28 19:25:58,592] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-11-28 19:25:58,605] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Write_csv_data_to_db> on 2020-11-28T13:55:46.743057+00:00
[2020-11-28 19:25:58,608] {standard_task_runner.py:54} INFO - Started process 36389 to run task
[2020-11-28 19:25:58,633] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Write_data_to_postgres_then_to_elasticsearch', 'Write_csv_data_to_db', '2020-11-28T13:55:46.743057+00:00', '--job_id', '459', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/csv_pg_elasticsearch.py', '--cfg_path', '/var/folders/ff/pqhf5klx0msdsn3m1cnq4cxr0000gn/T/tmp00g408yw']
[2020-11-28 19:25:58,635] {standard_task_runner.py:78} INFO - Job 459: Subtask Write_csv_data_to_db
[2020-11-28 19:25:58,680] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Write_data_to_postgres_then_to_elasticsearch.Write_csv_data_to_db 2020-11-28T13:55:46.743057+00:00 [running]> 47.43.168.192.in-addr.arpa
[2020-11-28 19:25:58,719] {taskinstance.py:1150} ERROR - extra data after last expected column
CONTEXT:  COPY sampletable, line 1: "2014-02-25,173.2,173.84343,101.62872,135.0,29886.7532397,3667985.39624,122.729470372"
Traceback (most recent call last):
  File "/Users/yudi/opt/anaconda3/envs/airflow/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/yudi/opt/anaconda3/envs/airflow/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/Users/yudi/opt/anaconda3/envs/airflow/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/yudi/airflow/dags/csv_pg_elasticsearch.py", line 65, in write_data
    cur.copy_from(f, "sampletable", sep=",")
psycopg2.errors.BadCopyFileFormat: extra data after last expected column
CONTEXT:  COPY sampletable, line 1: "2014-02-25,173.2,173.84343,101.62872,135.0,29886.7532397,3667985.39624,122.729470372"

[2020-11-28 19:25:58,722] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=Write_data_to_postgres_then_to_elasticsearch, task_id=Write_csv_data_to_db, execution_date=20201128T135546, start_date=20201128T135558, end_date=20201128T135558
[2020-11-28 19:26:03,680] {local_task_job.py:102} INFO - Task exited with return code 1
